

services:
  postgres:
    image: postgres:15-alpine
    container_name: ses_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_enterprise
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  migration:
    image: dimitri/pgloader:latest
    container_name: ses_migration
    depends_on:
      - postgres
    volumes:
      - .:/data
    networks:
      - app-network
    command: pgloader /data/scripts/pgloader.load
    profiles: [ "tools" ] # Only run when explicitly requested

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
