const { execSync } = require('child_process');
const path = require('path');
const fs = require('fs');

const APP_NAME = 'SmartEnterpriseSuite';
const APP_DISPLAY_NAME = 'Smart Enterprise Suite';
const EXE_PATH = path.join(__dirname, '..', 'dist', 'smart-enterprise-win-x64.exe');
const SERVICE_SCRIPT = path.join(__dirname, '..', 'backend', 'service-entry.js');

const command = process.argv[2];

function run(cmd, silent = false) {
  if (!silent) console.log(`> ${cmd}`);
  try {
    const out = execSync(cmd, { shell: true, encoding: 'utf8', stdio: 'pipe' });
    if (out && !silent) console.log(out);
    return out;
  } catch (e) {
    if (!silent) console.error(`Error: ${e.message}`);
    return null;
  }
}

function ensureServiceEntry() {
  const content = `
// Windows Service Entry Point
// This file is auto-generated by packaging/service-setup.js
const { spawn } = require('child_process');
const path = require('path');
const logFile = require('fs').createWriteStream(
  path.join(__dirname, '..', 'logs', 'service.log'),
  { flags: 'a' }
);
process.stdout.write = process.stderr.write = (data) => logFile.write(data);

const serverPath = path.join(__dirname, 'smart-enterprise-win-x64.exe');
const child = spawn(serverPath, [], {
  cwd: __dirname,
  detached: false,
  stdio: 'inherit'
});

child.on('exit', (code) => {
  logFile.end(\`Service exited with code \${code}\\n\`);
  process.exit(code);
});
`;
  fs.writeFileSync(SERVICE_SCRIPT, content);
  console.log(`Service entry script created at: ${SERVICE_SCRIPT}`);
}

function install() {
  console.log(`\n=== Installing ${APP_DISPLAY_NAME} as Windows Service ===\n`);
  
  if (!fs.existsSync(EXE_PATH)) {
    console.error(`ERROR: Executable not found at: ${EXE_PATH}`);
    console.error('Run "node packaging/build.js" first to create the executable.');
    process.exit(1);
  }

  ensureServiceEntry();

  // Stop existing service if running
  run(`sc stop ${APP_NAME}`, true);
  run(`sc delete ${APP_NAME}`, true);

  // Create service
  const result = run(`sc create ${APP_NAME} binPath= "${EXE_PATH}" DisplayName= "${APP_DISPLAY_NAME}" start= auto`);
  
  if (result !== null) {
    console.log('\n=== Service installed successfully ===');
    console.log('Run "sc query SmartEnterpriseSuite" to check status');
    console.log('Run "net start SmartEnterpriseSuite" to start');
    console.log('Run "node packaging/service-setup.js uninstall" to remove');
  } else {
    console.error('\nFailed to install service. Try running as Administrator.');
  }
}

function uninstall() {
  console.log(`\n=== Uninstalling ${APP_DISPLAY_NAME} Windows Service ===\n`);
  
  run(`sc stop ${APP_NAME}`);
  run(`sc delete ${APP_NAME}`);
  
  console.log('\n=== Service uninstalled ===');
}

function status() {
  const result = run(`sc query ${APP_NAME}`, true);
  if (result) {
    console.log(result);
  } else {
    console.log(`Service "${APP_NAME}" is not installed.`);
  }
}

function start() {
  run(`net start ${APP_NAME}`);
}

function stop() {
  run(`net stop ${APP_NAME}`);
}

const commands = {
  install,
  uninstall,
  status,
  start,
  stop
};

if (!command || !commands[command]) {
  console.log(`
Smart Enterprise Suite - Windows Service Manager

Usage: node service-setup.js <command>

Commands:
  install    - Install the app as a Windows Service (auto-start)
  uninstall  - Remove the Windows Service
  status     - Check service status
  start      - Start the service
  stop       - Stop the service

Examples:
  node packaging/service-setup.js install
  node packaging/service-setup.js status
  node packaging/service-setup.js uninstall
`);
  process.exit(command ? 1 : 0);
}

commands[command]();
